<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><EnableWindowsTargeting>true</EnableWindowsTargeting><UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>Kyla.Client</AssemblyName></PropertyGroup><ItemGroup><Compile Include="../Shared.cs" Link="Shared.cs"/></ItemGroup></Project>
